use consumer_behaviour;
select * from consumer;
##Q1 What is the total revenue generated by Male and Female customers?
select gender, sum(purchase_amount) revenue from consumer group by gender;

##Q2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, discount_applied, purchase_amount
from consumer
where discount_applied='Yes' and purchase_amount> (select avg(purchase_amount) from consumer)
group by customer_id, discount_applied,purchase_amount;

##Q3 Which are the top 5 products with highest average review rating?
select item_purchased as products, avg(review_rating) from consumer
group by products
order by 2 desc limit 5;

##Q4 Compare the average purchase amounts between Standard and Express shipping.
select shipping_type, avg(purchase_amount) avg_purchase  from consumer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

##Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscibers.
select discount_applied,count(customer_id) count_of_customer ,sum(purchase_amount) total_revenue ,  
avg(purchase_amount) avg_spend from consumer
group by discount_applied;

##Q6 Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
       ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
from consumer
group by item_purchased
order by discount_rate desc
limit 5;
	
##Q7 Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
CASE
	when previous_purchases between 0 and 3 then 'New'
    when previous_purchases between 3 and 16 then 'Returning'
    else 'Loyal'
end as consumer_segment,
COUNT(customer_id) AS total_customers
from consumer
group by consumer_segment;

##Q8 What are the top 3 most purchased product in each category.
with cte_1 as (
	select category, item_purchased,count(*) total, row_number() over(partition by category order by count(*) desc) ranks
	from consumer
	group by category, item_purchased
) select ranks,category, item_purchased, total 
from cte_1 
where ranks<=3
order by 1; 

##Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) total_buyers
from consumer
where previous_purchases >5
group by subscription_status;

##Q10 What is the revenue contribution of each age group?
select * from consumer;
select age_segment, sum(purchase_amount)
from consumer
group by age_segment
order by 2 desc;

##Complete